services:
  pihole:
    container_name: pihole
    image: 'pihole/pihole:latest'
    networks:
      default:
        ipv4_address: 172.21.3.11 # update as preferred
      pihole:
        ipv4_address: 192.168.1.11 # update as preferred and following router ip address, e.g. 192.168.1.25
      wg-easy:
        ipv4_address: 10.8.2.11 # update as preferred
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8880:80/tcp"
    environment:
      TZ: 'America/Los_Angeles' # update as preferred
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  nginxproxymanager:
    container_name: nginxproxymanager
    image: 'jc21/nginx-proxy-manager:latest' 
    networks:
      default:
        ipv4_address: 172.21.3.21 # update as preferred
      wg-easy:
        ipv4_address: 10.8.2.21 # update as preferred
    ports:
      - '80:80'
      - '127.0.0.1:81:81'
      - '443:443' 
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 30s
      timeout: 5s
      retries: 3    
    depends_on:
      pihole:
        condition: service_healthy
    restart: unless-stopped 
  
  wg-easy:
    container_name: wg-easy
    image: 'ghcr.io/wg-easy/wg-easy'
    volumes:
      - ./wg-easy/etc_wireguard:/etc/wireguard
    networks:
      wg-easy:
        ipv4_address: 10.8.2.31 # update as preferred
    ports:
      - "51820:51820/udp"
      - "127.0.0.1:51821:51821/tcp"
    environment:
      - LANG=en
      - WG_HOST= [YOUR DOMAIN] # use your domain or get a subdomain from a DDNS service e.g. Duck DNS
      - PASSWORD_HASH= [YOUR PASSWORD HASH] # generate bcrypt password hash from your password. See https://github.com/wg-easy/wg-easy/blob/master/README.md for more details
      - WG_DEFAULT_DNS=10.8.2.11 # your pihole IP address on the wg-easy network set in the pihole section
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    depends_on:
      pihole:
        condition: service_healthy
      nginxproxymanager:
        condition: service_healthy

volumes:
  etc_wireguard:

networks:
  default:
    name: npm
    ipam:
      config:
        - subnet: 172.21.3.0/24
  pihole:
    name: pihole
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.1.0/24 # update following your router IP address
          gateway: 192.168.1.1 # use your router IP address
  wg-easy:
    name: wg-easy
    ipam:
      config:
        - subnet: 10.8.2.0/24
